name: "grocery_app"
dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.4
  freezed_annotation: ^2.1.0
  http: ^0.13.5
  json_annotation: ^4.6.0
environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.1
  flutter_test: 
    sdk: flutter
  freezed: ^2.1.0+1
    
  json_serializable: ^6.3.1
